### PR TITLE
fix: nullability semantics of predicates in JoinRel and FilterRel

### LINKED ISSUE #51: Double-check whether predicate expressions have correct nullability semantics
When I wrote the bulk of the validation code, I was properly confused about nullable booleans in the context of predicate expressions (both things that want one, and things that return one, like set containment subqueries). There is a good summary about what the behavior of these things *should* be [here](https://github.com/substrait-io/substrait/issues/325#issuecomment-1244578057), but it's probably worth double-checking corner cases against query engine documentation or just by experimentation. When a nullable boolean is received by a predicate expression slot, the validator should probably also emit a note of some kind about what null means in that particular context.

### PR DESCRIPTION
**Pull request by mbrobbel**
An attempt to fix part of #51.

- [x] Filter relations
  According to https://github.com/substrait-io/substrait/issues/325#issuecomment-1244578057: 
  > For those boolean expressions, true is treated as "succeeds" and false and unknown (aka null) are treated as "fails".
  
  I modified the summary of filter relations to reflect this behavior.

- [x] Join relations
  - [x] ~According to https://github.com/substrait-io/substrait/blob/e68fdc049c1219a1269225456072d7548c83f297/site/docs/relations/logical_relations.md?plain=1#L199, literal join expression values are allowed, but they must be `true`. Added a check and test.~
  - [x] Added some notes to the summary of join relations about nullability behavior of the join and post join filter predicates.

I've added comment tests to the test runner to test these changes.

### CODE REVIEW

File: rs/src/parse/relations/filter.rs [hunk 1]
```diff
@@ -32,14 +32,10 @@ pub fn parse_filter_rel(
     describe!(y, Relation, "Filter by {}", &predicate);
     summary!(
         y,
-        "This relation discards all rows for which {} yields false.",
-        &predicate
+        "This relation discards all rows for which the expression {} yields {}.",
```
Comment (mbasmanova) [inline rs/src/parse/relations/filter.rs:35]: Thank you for the fix.

I'm confused by "nullable" flag here. In SQL, all types are nullable, e.g. value of any type can be null. I'm curious which systems are expected to specify nullable as false.

Comment (mbrobbel) [reply rs/src/parse/relations/filter.rs:35]: In substrait types can be non-nullable ([e.g. booleans](https://github.com/substrait-io/substrait/blob/a79eb07a15cfa157e795f028a83f746967c98805/proto/substrait/type.proto#L58)). A scalar function from an extension could return a non-nullable boolean. This change reflects that.

Comment (jvanstraten) [reply rs/src/parse/relations/filter.rs:35]: Substrait's type system is strictly typed and actually uses non-nullable by default; please review https://substrait.io/types/type_system/. As for why, that's a question more suited for slack or maybe the mailing list I suppose. It was built this way before @mbrobbel or I joined the project.

Comment (jvanstraten) [reply rs/src/parse/relations/filter.rs:35]: The default behavior for Substrait functions is that the return type is nullable if and only if any of the arguments is nullable. This is covered by [`MIRROR` nullability behavior](https://substrait.io/expressions/scalar_functions/#nullability-handling). With the "by default" thing I just mean that if you write `i32` you're actually talking about a non-nullable 32-bit integer, whereas you need to write `i32?` to talk about a nullable 32-bit integer. We could have used `i32!` for non-nullable and `i32` for nullable, too (or just require either ! or ? if you want to consider nullability). It's just a notation convention thing.

Comment (jvanstraten) [reply rs/src/parse/relations/filter.rs:35]: As for the "why" part by the way, I can't speak for the community because I don't know the reasons, but as a more back-end/hardware guy, I'd say that not just allowing everything to basically fail silently by default is a good thing. `null` is hardly treated in a consistent manner, so being able to avoid it or make assertions that an expression can never fail that way is also a good thing. It's certainly true though that for a practical plan using SQL-esque functions and relations, the vast majority of your types are going to be null.

I suppose part of it is also that we're representing a whole row/record as a single struct in some contexts. That struct is never nullable, even in SQL; there is no way to have a row that is "so null" that it doesn't even have any fields anymore. This generalization is, again, really nice when you're actually implementing these things and want to support nested types (which, AFAICT, SQL generally does not support, but Substrait does). It prevents you from having to implement column/field access and nested struct field access separately.

Comment (mbasmanova) [reply rs/src/parse/relations/filter.rs:35]: > With the "by default" thing I just mean that if you write i32 you're actually talking about a non-nullable 32-bit integer, whereas you need to write i32? to talk about a nullable 32-bit integer. 

@jvanstraten This is very helpful clarification. Thanks.

@chaojun-zhang We need to make sure we use i32? and similar when defining custom function signatures in https://github.com/facebookincubator/velox/pull/2496

Comment (mbasmanova) [reply rs/src/parse/relations/filter.rs:35]: > I suppose part of it is also that we're representing a whole row/record as a single struct in some contexts. That struct is never nullable, even in SQL

I understand this point. In Velox, we also use RowVector represent both a struct field and a top-level row, which like you pointed out cannot possibly be null.

> This generalization is, again, really nice when you're actually implementing these things and want to support nested types (which, AFAICT, SQL generally does not support, but Substrait does).

Modern SQL engines (Spark, Presto, Trino, Velox at least) do support complex types and also support higher order functions / lambdas. For example, transform in Presto: https://prestodb.io/docs/current/functions/array.html#transform

I'm curious if lambda functions are supported in Substrait as well and, if so, what is the type of the "function" argument in these?

Comment (jvanstraten) [reply rs/src/parse/relations/filter.rs:35]: > We need to make sure we use i32? and similar when defining custom function signatures

Be aware that it won't do anything unless you also specify `DISCRETE` nullability, because the nullability flags end up getting "overridden" by the semantics of `MIRROR` or (for arguments) `DECLARED_OUTPUT`. This and the other logic behind [type derivations](https://substrait.io/expressions/scalar_functions/#output-type-derivation) are, honestly, super weird, and have been causing me headaches for over half a year now to try to get them into the validator, so if something doesn't make sense to you there, it might well be because it just doesn't. I'm working on it.

> I'm curious if lambda functions are supported in Substrait as well and, if so, what is the type of the "function" argument in these?

They're not, but only because no one has bothered to define them yet. I thought about them for a bit in https://github.com/substrait-io/substrait/issues/320 because some functions naturally take a comparator lambda for sort-like semantics, which currently can't be done. I figured that, since we don't really have a concept of statements, a lambda function would just be written like a normal expression, but with argument references at the leaves rather than (only) field references and literals. The types of those would just be whatever the function you're passing the lambda to as an argument defines them to be.

This is not as powerful as generalized lambdas that you can pass around as values, though. A more general solution, with that lambda data type, would probably look something like `lambda<struct<arg0, arg1, ...>, return>`, in which case the argument types would need to be defined along with the argument references in the expression tree (or, better yet, in the special expression type that constructs the lambda), and then matched against the function prototype that will be calling them (rather than derived by the prototype).

File: rs/src/parse/relations/join.rs [hunk 2]
```diff
@@ -38,10 +38,24 @@ pub fn parse_join_rel(x: &substrait::JoinRel, y: &mut context::Context) -> diagn
...
+            expressions::literals::LiteralValue::Boolean(true)
+        ) {
+            diagnostic!(
+                y,
+                Error,
+                ExpressionIllegalLiteralValue,
+                "literal join expression value must be true"
+            );
+        }
+    }
```
Comment (jvanstraten) [inline rs/src/parse/relations/join.rs:58]: > literal join expression value must be true

Does it? I mean, yeah, to get a plan that makes any kind of sense, sure, but I don't think it is or should be illegal to do it, just like how `if false { ... }` isn't illegal. Errors and warnings are very strictly only dealt out to plans that are actually illegal, because the validity verdict is derived from it.

If this is something you really want to detect, you could emit a comment, or throw an info diagnostic in (I guess) the `Redundant` class (the JoinRel becomes kind of redundant at that point, since it would always emit zero rows, or in case of an anti join emit the LHS unchanged, I think).

File: rs/src/parse/relations/join.rs [hunk 3]
```diff
@@ -106,59 +122,81 @@ pub fn parse_join_rel(x: &substrait::JoinRel, y: &mut context::Context) -> diagn
...
+Returns a row for each row from the left input, concatenating
+it with the row from the right input for which the join
+expression yields true. If the expression never yields true for
+a left input, the fields corresponding to the right input are
+set to null. If the expression yields true for a left row and
+multiple right rows, this may return the first pair encountered
+or throw an error."
+                .to_string(),
+        }),
+    );
```
Comment (jvanstraten) [inline rs/src/parse/relations/join.rs:190]: I don't really like this string style. For one thing, I hate multiline strings that break the indentation flow of the code, but I'm also not 100% sure what happens or should happen with newlines in these strings currently. I guess they don't break anything in HTML and aren't used in the plantext output because they're not diagnostics, but via protobuf export you could probably get the original strings back. I'd rather have them not put arbitrarily-placed newlines in them.

I guess the `concat!` thing can be replaced with a properly indented multiline string by just escaping the newlines, though? When I wrote it I probably wasn't aware or sure that Rust also removes indentation following an escaped newline (making the newline escape actually useful; looking at you, Python).

**Review by jvanstraten — CHANGES_REQUESTED** [review]

File: rs/src/parse/relations/join.rs (hunk 2 above)
Comment (mbrobbel) [reply rs/src/parse/relations/join.rs:58]: I agree with you, but I'm just following the [spec](https://github.com/substrait-io/substrait/blob/e68fdc049c1219a1269225456072d7548c83f297/site/docs/relations/logical_relations.md?plain=1#L199) here.

Comment (jvanstraten) [reply rs/src/parse/relations/join.rs:58]: All I see is

> Can be the literal True.

That doesn't mean it can't be the literal false, or any other expression. It just clarifies that it's legal to turn a JoinRel into a full cross product this way, despite the expression itself being required.

File: rs/src/parse/relations/join.rs (hunk 3 above)
Comment (mbrobbel) [reply rs/src/parse/relations/join.rs]: How about [c463c86](https://github.com/substrait-io/substrait-validator/pull/52/commits/c463c864c2826614daa7c3c15d4f820af977045d)?

Comment (jvanstraten) [reply rs/src/parse/relations/join.rs]: I normally align the string contents to the same column as the first `"` rather than the first character of the string (and don't think cargo fmt has an opinion about this, unfortunately), but I'm fine with this.

**Comment by mbrobbel** [comment]
@jvanstraten do you prefer a single PR to fix #51, or should I split over multiple PRs? If we're doing multiple PRs, this one is ready for review.

File: rs/src/parse/relations/join.rs [hunk 4]
```diff
@@ -106,59 +105,73 @@ pub fn parse_join_rel(x: &substrait::JoinRel, y: &mut context::Context) -> diagn
...
+    } else {
+        "false"
+    };
+    y.push_summary(
+        comment::Comment::new().nl().plain(match join_type {
+            JoinType::Unspecified => "".to_string(),
+            JoinType::Inner => format!(
+                "Returns rows combining the row from the left and right \
+                input for each pair where the join expression yields true. \
+                Discarding rows where the join expression yields {}.",
```
Comment (jvanstraten) [inline rs/src/parse/relations/join.rs:119]: This doesn't seem very grammatically correct;
```suggestion
                "Returns rows combining the row from the left and right \
                input for each pair where the join expression yields true, \
                discarding rows where the join expression yields {}.",
```
Likewise for the other options.

**Review by jvanstraten — CHANGES_REQUESTED** [review]

**Review by jvanstraten — APPROVED** [review]
